### ISSUE TITLE
Bug with wiped world and sql db when creating faction

### ISSUE THREAD

**Issue by Death666Machine** [foogs/FoogsProjects#25]
22:39:23.9614 [WARN]   ServerJump: Something wrong with MySQL InsertFactionInfoMySql.Data.MySqlClient.MySqlException (0x80004005): Column 'modifytime' cannot be null
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at ServerJumpNS.FactionAndPlyersSync.ConnectToMySql.InsertFactionInfo(UInt64 founderSteamId, Int64 factionId, String factionTag, String factionName, String factionDescription, String factionPrivateInfo, String memberarray) in C:\Users\Foogs\Documents\Visual Studio 2017\Projects\ServerJump\FactionAndPlyersSync\MySQLConnect.cs:line 376
22:39:23.9614 [WARN]   ServerJump: (FactionCreateIntercept) Faction [tes]test created, result = False
22:39:50.7151 [WARN]   ServerJump: System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at MySql.Data.MySqlClient.MySqlDataReader.GetFieldValue(Int32 index, Boolean checkNull)
   at MySql.Data.MySqlClient.MySqlDataReader.GetUInt64(Int32 column)
   at ServerJumpNS.FactionAndPlyersSync.ConnectToMySql.CheckForNewFactions(Boolean usetime, DateTime lasttime, UInt32 lastknownid) in C:\Users\Foogs\Documents\Visual Studio 2017\Projects\ServerJump\FactionAndPlyersSync\MySQLConnect.cs:line 1186

**Comment by foogs** [comment]
u have a bad mysql server/version. NULL is allowed to use.
INSERT INTO `Factions` (`id`, `founderId`, `factionId`, `factionTag`, `factionName`, `factionDescription`, `factionPrivateInfo`, `members`, `modifytime`, `deleted`) VALUES ('4', '5466456', '3453645345', 'fffgf', 'df6gdftgdfg', 'dfgdfgdfg', 'dfgdft', NULL, CURRENT_TIMESTAMP, '0');
